atualizando arquivo .yml

diff --git a/.github/workflows/analisePR.yml b/.github/workflows/analisePR.yml
--- a/.github/workflows/analisePR.yml
+++ b/.github/workflows/analisePR.yml
@@ -14,12 +14,26 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      # Authenticate and get token
+      - name: Authenticate and Get Token
+        id: authenticate
+        run: |
+          auth_response=$(curl -s --location \
+            --request POST 'https://idm.stackspot.com/itau/oidc/oauth/token' \
+            --header 'Content-Type: application/x-www-form-urlencoded' \
+            --data-urlencode 'client_id=f7c15ec6-98d7-4dec-b2db-39db51bd9e46' \
+            --data-urlencode 'grant_type=client_credentials' \
+            --data-urlencode 'client_secret=357JeEbqdnzE1792Y8M49Mb57bvuZxXZ5VijPY335N1HYrVrWwPKsANnE1x6h3QM')
+          access_token=$(echo $auth_response | jq -r '.access_token')
+          echo "access_token=$access_token" >> $GITHUB_ENV
+
       # Call API to start execution
       - name: Start API Execution
         id: start_execution
         run: |
           response=$(curl -s -X POST "https://genai-code-buddy-api.stackspot.com/v1/quick-commands/create-execution/validador-pr" \
             -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${{ env.access_token }}" \
             -d '{"message":"Validando pull request para a branch principal"}')
           execution_id=$(echo $response | jq -r '.executionID')
           echo "execution_id=$execution_id" >> $GITHUB_ENV
@@ -30,8 +44,8 @@ jobs:
         run: |
           status=""
           while [ "$status" != "COMPLETED" ]; do
-            response=$(curl -s -X GET "https://genai-code-buddy-api.stackspot.com/v1/quick-commands/callback/{execution_id}" \
-              -H "Authorization: Bearer YOUR_ACCESS_TOKEN")
+            response=$(curl -s -X GET "https://genai-code-buddy-api.stackspot.com/v1/quick-commands/callback/${{ env.execution_id }}" \
+              -H "Authorization: Bearer ${{ env.access_token }}")
             status=$(echo $response | jq -r '.progress.status')
             echo "Current status: $status"
             if [ "$status" == "FAILED" ]; then
@@ -42,6 +56,10 @@ jobs:
           done
           result=$(echo $response | jq -r '.result')
           echo "Execution completed. Result: $result"
+          if [ "$result" == "false" ]; then
+            echo "Validation failed. Blocking PR merge."
+            exit 1
+          fi
 
       # Run lint check
       - name: Run Lint
